### ISSUE TITLE
[TASK] Compatibility with PHP 7.1 and TYPO3 8

### ISSUE THREAD

**Issue by dhuf** [sinso/ext-translationapi#7]

**Comment by fanat98** [comment]
@dhuf any errors with 7.1?

**Comment by dhuf** [comment]
@fanat98 no problem, but it is just not defined in the emconf

**Comment by xperseguers** [comment]
Ah, you forgot to reference (and thus close) this ticket with your PR.

Next time, just add such comment in commit message:

```
[TASK] Whatever

Resolves: #7
```
